version: '3'

services:
  mac2ip:
    build: .
    image: mac2ip
    ports:
      - "8081:8080"
    environment:
      DB_NAME: devices
      DB_HOST: db
      DB_USER: my_user
      DB_PASS: my_pass
      DRP_INSTANCE: "drp-hostname"

  db:
    image: postgres:11.2
    environment:
      POSTGRES_DB: devices
      POSTGRES_USER: my_user
      POSTGRES_PASSWORD: my_pass
    volumes:
      - ./data:/var/lib/postgresql/data
